ROOT: '/storage/groups/ml01/workspace/ignacio.ibarra/theislab/retinal_scRNAseq_integration/data/integration_march_2021/output'
r_env : scIB-R-integration
py_env : scIB-python
conv_env : scIB-R-conversion
timing: false

unintegrated_metrics: false

FEATURE_SELECTION:
  HVG.1K: 1000
  # HVG.2K: 2000
  # HVG.3K: 3000

# full_feature: 0

SCALING:
  - unscaled
  # - scaled

METHODS: # method name : ouput type(s)
$METHODS_QUERY

DATA_SCENARIOS:
$DATA_SCENARIOS_QUERY
